sudo: required
dist: trusty
branches:
  only:
    - master
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install colorgcc
  - sudo sh doc/dependencies.sh
install:
  - ./bootstrap
  - ./configure CC=colorgcc
  - make -j
script:
  - make check -j
