language: c
compiler:
  - gcc
before_install:
- sudo add-apt-repository ppa:dns/gnu --yes
- sudo apt-get update
- sudo apt-get install autoconf automake libtool pandoc libswscale-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libreadline-dev libmjpegtools-dev
- sudo apt-get install pkg-config libgmp-dev libunistring-dev libffi-dev libgc-dev
- wget ftp://ftp.cs.tu-berlin.de/pub/gnu/guile/guile-2.0.11.tar.gz
- tar xzf guile-2.0.11.tar.gz
- cd guile-2.0.11
- ./configure
- make
- sudo make install
- cd ..
install:
- export LD_LIBRARY_PATH=/usr/local/lib
- make -f Makefile.dist
- ./configure
- make
script:
- make check
