sudo: required
dist: trusty
branches:
  only:
    - master
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install -q --yes build-essential autoconf automake libtool devscripts equivs
  - cp control.ubuntu:trusty debian/control
  - sudo mk-build-deps --install --remove --tool 'apt-get -q --yes' debian/control
install:
  - ./bootstrap
  - ./configure
  - make -j
script:
  - make check -j
