# http://ansible.pickle.io/post/86598332429/running-ansible-playbook-in-localhost
# ansible-playbook -i "localhost," -c local aiscm.yml -K
---
- hosts: all
  tasks:
  - name: install build tools
    apt: name={{item}} state=latest update_cache=yes
    with_items:
    - build-essential
    - autoconf
    - automake
    - libtool
    - colorgcc
    sudo: true
    tags: tools
  - name: install required packages
    apt: name={{item}} state=latest update_cache=yes
    with_items:
    - guile-2.0-dev
    - linux-libc-dev
    - libmjpegtools-dev
    - imagemagick
    - libmagickcore-dev
    - libpulse-dev
    - libjpeg-dev
    - libx11-dev
    - libxext-dev
    - libxv-dev
    - libxmu-dev
    - libxi-dev
    - libglu1-mesa-dev
    - libgl1-mesa-dev
    - libswscale-dev
    - libavutil-dev
    - libavcodec-dev
    - libavformat-dev
    - pandoc
    sudo: true
    tags: dependencies
  - name: bootstrap build scripts
    command: ./bootstrap
    tags: build
  - name: configure build
    command: ./configure CC=colorgcc
    tags: build
  - name: compile
    command: make -j
    tags: build
  - name: create source archive
    command: make dist-xz
    tags: distributable
  - name: run test suite
    command: make check -j
    tags: test
